import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Tutorial sidebar - excludes the POC directories
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  
  // My Next Home POC sidebar
  mynexthomepocSidebar: [
    {
      type: 'autogenerated',
      dirName: 'mynexthomepoc',
    },
  ],
  
  // Next Business Idea POC sidebar
  nextbusideapocSidebar: [
    {
      type: 'autogenerated',
      dirName: 'nextbusideapoc',
    },
  ],
  
  // birddogger sidebar
  birddoggerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'birddogger',
    },
  ],
  
  // nextinvestment sidebar
  nextinvestmentSidebar: [
    {
      type: 'autogenerated',
      dirName: 'nextinvestment',
    },
  ],
  // dnamatches sidebar
  dnamatchesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dnamatches',
    },
  ],
  // mynexthome sidebar
  mynexthomeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'mynexthome',
    },
  ],
  // phonemessagescraper sidebar
  phonemessagescraperSidebar: [
    {
      type: 'autogenerated',
      dirName: 'phonemessagescraper',
    },
  ],
  
  // modern-mama sidebar
  'modern-mamaSidebar': [
    {
      type: 'autogenerated',
      dirName: 'modern-mama',
    },
  ],
  // jobscheduling sidebar
  jobschedulingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'jobscheduling',
    },
  ],
};

export default sidebars;
