import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Tutorial sidebar - excludes the POC directories
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  
  // My Next Home POC sidebar
  mynexthomepocSidebar: [
    {
      type: 'autogenerated',
      dirName: 'mynexthomepoc',
    },
  ],
  
  // Next Business Idea POC sidebar
  nextbusideapocSidebar: [
    {
      type: 'autogenerated',
      dirName: 'nextbusideapoc',
    },
  ],
  // Bird Dogger sidebar
  birddoggerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'birddogger',
    },
  ],
};

export default sidebars;
