name: Sync project docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-docs]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout documentation-site
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout mynexthomepoc
        uses: actions/checkout@v4
        with:
          repository: mwinfiel0331/mynexthomepoc
          ref: main
          path: _source_mynexthomepoc

      - name: Checkout nextbusideapoc
        uses: actions/checkout@v4
        with:
          repository: mwinfiel0331/nextbusideapoc
          ref: main
          path: _source_nextbusideapoc

      - name: Sync docs folders
        run: |
          # Sync mynexthomepoc docs
          if [ -d "_source_mynexthomepoc/docs" ]; then
            rm -rf docs/mynexthomepoc
            mkdir -p docs/mynexthomepoc
            rsync -a --delete _source_mynexthomepoc/docs/ docs/mynexthomepoc/
          fi
          
          # Sync nextbusideapoc docs
          if [ -d "_source_nextbusideapoc/docs" ]; then
            rm -rf docs/nextbusideapoc
            mkdir -p docs/nextbusideapoc
            rsync -a --delete _source_nextbusideapoc/docs/ docs/nextbusideapoc/
          fi
          
          # Clean up source directories
          rm -rf _source_mynexthomepoc _source_nextbusideapoc

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are any changes in the docs directories
          if [ -n "$(git status --porcelain docs/)" ]; then
            git add docs/
            git commit -m "Sync docs from source repos"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi