name: Sync project docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-docs]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout documentation-site
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout mynexthomepoc
        uses: actions/checkout@v4
        with:
          repository: mwinfiel0331/mynexthomepoc
          ref: main
          path: _source_mynexthomepoc

      - name: Checkout nextbusideapoc
        uses: actions/checkout@v4
        with:
          repository: mwinfiel0331/nextbusideapoc
          ref: main
          path: _source_nextbusideapoc

      - name: Sync docs folders
        run: |
          rm -rf docs/mynexthomepoc/docs
          mkdir -p docs/mynexthomepoc
          rsync -a --delete _source_mynexthomepoc/docs/ docs/mynexthomepoc/docs/
          
          rm -rf docs/nextbusideapoc/docs
          mkdir -p docs/nextbusideapoc
          rsync -a --delete _source_nextbusideapoc/docs/ docs/nextbusideapoc/docs/

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/mynexthomepoc docs/nextbusideapoc
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync docs from source repos"
            git push
          fi